spring.application.name=TicketSystem

#logs for all the queries
server.error.include-stacktrace=ALWAYS
server.port=8080
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketSystem
spring.datasource.username=postgres
spring.datasource.password=XXXXXX

spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=XXX
spring.mail.username=zalmatooq31@gmail.com
spring.mail.password=XXXXXXXXXXXXX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true